debugging

diff --git a/.github/workflows/portal-app-CI.yaml b/.github/workflows/portal-app-CI.yaml
--- a/.github/workflows/portal-app-CI.yaml
+++ b/.github/workflows/portal-app-CI.yaml
@@ -36,52 +36,52 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_REGION }}
 
-############################ Pre Build Phase ###################################
-    ### Run Trivy FS Scan
-      - name: Run Trivy FS Scan (Repository Dependencies)
-        uses: aquasecurity/trivy-action@0.28.0
-        with:
-          scan-type: 'fs'
-          ignore-unfixed: true
-          format: 'table'
-          exit-code: 1
-          severity: 'CRITICAL,HIGH' 
+# ############################ Pre Build Phase ###################################
+#     ### Run Trivy FS Scan
+#       - name: Run Trivy FS Scan (Repository Dependencies)
+#         uses: aquasecurity/trivy-action@0.28.0
+#         with:
+#           scan-type: 'fs'
+#           ignore-unfixed: true
+#           format: 'table'
+#           exit-code: 1
+#           severity: 'CRITICAL,HIGH' 
 
-    ### SonarQube Scane for code analysis
-      - name: Code analysis
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: |
-          npx sonarqube-scanner \
-          -Dsonar.projectKey=portal-app \
-          -Dsonar.sources=app-Frontend/public \
-          -Dsonar.host.url=https://sonarqube.spontansolutions.com/ \
-          -Dsonar.login=$SONAR_TOKEN
+#     ### SonarQube Scane for code analysis
+#       - name: Code analysis
+#         env:
+#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+#         run: |
+#           npx sonarqube-scanner \
+#           -Dsonar.projectKey=portal-app \
+#           -Dsonar.sources=app-Frontend/public \
+#           -Dsonar.host.url=https://sonarqube.spontansolutions.com/ \
+#           -Dsonar.login=$SONAR_TOKEN
     
-    ### Wait for SonarQube Analysis
-      - name: Wait for SonarQube Analysis
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: |
-          STATUS="PENDING"
-          while [ "$STATUS" == "PENDING" ]; do
-            sleep 20
-            RESPONSE=$(curl -s -u $SONAR_TOKEN: "https://sonarqube.spontansolutions.com/api/qualitygates/project_status?projectKey=portal-app")
-            STATUS=$(echo "$RESPONSE" | jq -r '.projectStatus.status' || echo "PENDING")
-            echo "Waiting for SonarQube Analysis... Current Status: $STATUS"
-          done
+#     ### Wait for SonarQube Analysis
+#       - name: Wait for SonarQube Analysis
+#         env:
+#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+#         run: |
+#           STATUS="PENDING"
+#           while [ "$STATUS" == "PENDING" ]; do
+#             sleep 20
+#             RESPONSE=$(curl -s -u $SONAR_TOKEN: "https://sonarqube.spontansolutions.com/api/qualitygates/project_status?projectKey=portal-app")
+#             STATUS=$(echo "$RESPONSE" | jq -r '.projectStatus.status' || echo "PENDING")
+#             echo "Waiting for SonarQube Analysis... Current Status: $STATUS"
+#           done
 
-    ### SonarQube Quality Gates
-      - name: Check SonarQube Quality Gate
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: |
-          STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonarqube.spontansolutions.com/api/qualitygates/project_status?projectKey=portal-app" | jq -r .projectStatus.status)
-          echo $STATUS
-          if [ "$STATUS" != "OK" ]; then
-            echo "❌ ❌ Quality Gate Failed. Stoping deployment!! ❌ ❌ "
-            exit 1
-          fi
+#     ### SonarQube Quality Gates
+#       - name: Check SonarQube Quality Gate
+#         env:
+#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+#         run: |
+#           STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonarqube.spontansolutions.com/api/qualitygates/project_status?projectKey=portal-app" | jq -r .projectStatus.status)
+#           echo $STATUS
+#           if [ "$STATUS" != "OK" ]; then
+#             echo "❌ ❌ Quality Gate Failed. Stoping deployment!! ❌ ❌ "
+#             exit 1
+#           fi
 
 #################################### Build Phase ########################################
 
@@ -108,52 +108,52 @@ jobs:
           cd app-Frontend
           tar -czf portal-app-$DATE.tar.gz node_modules package.json public portal-app.js
 
-    ### Uploading Artifact to Nexus
-      - name: Upload to Nexus
-        run: |
-          curl -u ${{ secrets.NEXUS_USER }}:${{ secrets.NEXUS_PASS }} \
-          --upload-file app-Frontend/portal-app-$DATE.tar.gz \
-          https://nexus.spontansolutions.com/repository/portal-app-artifacts/portal-app-$DATE.tar.gz
+    # ### Uploading Artifact to Nexus
+    #   - name: Upload to Nexus
+    #     run: |
+    #       curl -u ${{ secrets.NEXUS_USER }}:${{ secrets.NEXUS_PASS }} \
+    #       --upload-file app-Frontend/portal-app-$DATE.tar.gz \
+    #       https://nexus.spontansolutions.com/repository/portal-app-artifacts/portal-app-$DATE.tar.gz
 
-    ### Uploading Artifact to S3
-      - name: Uploading Artifact to S3 Bucket
-        run: |
-          cd app-Frontend
-          aws s3 cp portal-app-$DATE.tar.gz s3://portal-app-spontansolutions/github-actions/
+    # ### Uploading Artifact to S3
+    #   - name: Uploading Artifact to S3 Bucket
+    #     run: |
+    #       cd app-Frontend
+    #       aws s3 cp portal-app-$DATE.tar.gz s3://portal-app-spontansolutions/github-actions/
 
-    ### Build Docker Image
-      - name: Build Portal-app Docker Image
-        uses: docker/build-push-action@v6
-        with:
-          context: app-Frontend
-          dockerfile: Dockerfile
-          push: false
-          tags: ${{ secrets.DOCKERHUB_USERNAME }}/portal-app:${{ env.DATE }}
+    # ### Build Docker Image
+    #   - name: Build Portal-app Docker Image
+    #     uses: docker/build-push-action@v6
+    #     with:
+    #       context: app-Frontend
+    #       dockerfile: Dockerfile
+    #       push: false
+    #       tags: ${{ secrets.DOCKERHUB_USERNAME }}/portal-app:${{ env.DATE }}
 
-      - name: Scan local Docker image with Trivy
-        uses: aquasecurity/trivy-action@0.28.0
-        with:
-          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/portal-app:${{ env.DATE }}
-          format: 'table'
-          ignore-unfixed: true
-          exit-code: 0
-          severity: 'CRITICAL,HIGH'
+    #   - name: Scan local Docker image with Trivy
+    #     uses: aquasecurity/trivy-action@0.28.0
+    #     with:
+    #       image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/portal-app:${{ env.DATE }}
+    #       format: 'table'
+    #       ignore-unfixed: true
+    #       exit-code: 0
+    #       severity: 'CRITICAL,HIGH'
 
-    ### Docker Login
-      - name: Login Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_PASSWORD }}
+    # ### Docker Login
+    #   - name: Login Docker Hub
+    #     uses: docker/login-action@v3
+    #     with:
+    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
+    #       password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
-    ### Push to Docker Hub
-      - name: Push Portal-app to Docker Hub
-        uses: docker/build-push-action@v6
-        with:
-          context: app-Frontend
-          dockerfile: Dockerfile
-          push: true
-          tags: ${{ secrets.DOCKERHUB_USERNAME }}/portal-app:${{ env.DATE }}
+    # ### Push to Docker Hub
+    #   - name: Push Portal-app to Docker Hub
+    #     uses: docker/build-push-action@v6
+    #     with:
+    #       context: app-Frontend
+    #       dockerfile: Dockerfile
+    #       push: true
+    #       tags: ${{ secrets.DOCKERHUB_USERNAME }}/portal-app:${{ env.DATE }}
 
 
 ############################## CD ###############################################
@@ -162,10 +162,12 @@ jobs:
         run: |
           git clone ${{ secrets.GIT_OPS_REPO }}
           cd git-ops-ArgoCD
+          ls -R
 
       - name: Update Deployment YAML
         run: |
           cd portal-app/app-Frontend-kubernetes
+          ls
           sed -i "s|\(image: .*\):.*|\1:${{ env.DATE }}|" deployment.yml
 
       - name: Commit and Push to GitOps Repo
