debugging

diff --git a/.github/workflows/portal-app-CI.yaml b/.github/workflows/portal-app-CI.yaml
--- a/.github/workflows/portal-app-CI.yaml
+++ b/.github/workflows/portal-app-CI.yaml
@@ -47,43 +47,43 @@ jobs:
           exit-code: 1
           severity: 'CRITICAL,HIGH' 
 
-    ### SonarQube Scane for code analysis
-      - name: Code analysis
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: |
-          npx sonarqube-scanner \
-          -Dsonar.projectKey=portal-app \
-          -Dsonar.sources=app-Frontend/public \
-          -Dsonar.host.url=https://sonarqube.spontansolutions.com/ \
-          -Dsonar.login=$SONAR_TOKEN
+    # ### SonarQube Scane for code analysis
+    #   - name: Code analysis
+    #     env:
+    #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+    #     run: |
+    #       npx sonarqube-scanner \
+    #       -Dsonar.projectKey=portal-app \
+    #       -Dsonar.sources=app-Frontend/public \
+    #       -Dsonar.host.url=https://sonarqube.spontansolutions.com/ \
+    #       -Dsonar.login=$SONAR_TOKEN
     
-    ### Wait for SonarQube Analysis
-      - name: Wait for SonarQube Analysis
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: |
-          STATUS="PENDING"
-          while [ "$STATUS" == "PENDING" ]; do
-            sleep 20
-            RESPONSE=$(curl -s -u $SONAR_TOKEN: "https://sonarqube.spontansolutions.com/api/qualitygates/project_status?projectKey=portal-app")
-            STATUS=$(echo "$RESPONSE" | jq -r '.projectStatus.status' || echo "PENDING")
-            echo "Waiting for SonarQube Analysis... Current Status: $STATUS"
-          done
+    # ### Wait for SonarQube Analysis
+    #   - name: Wait for SonarQube Analysis
+    #     env:
+    #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+    #     run: |
+    #       STATUS="PENDING"
+    #       while [ "$STATUS" == "PENDING" ]; do
+    #         sleep 20
+    #         RESPONSE=$(curl -s -u $SONAR_TOKEN: "https://sonarqube.spontansolutions.com/api/qualitygates/project_status?projectKey=portal-app")
+    #         STATUS=$(echo "$RESPONSE" | jq -r '.projectStatus.status' || echo "PENDING")
+    #         echo "Waiting for SonarQube Analysis... Current Status: $STATUS"
+    #       done
 
-    ### SonarQube Quality Gates
-      - name: Check SonarQube Quality Gate
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: |
-          STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonarqube.spontansolutions.com/api/qualitygates/project_status?projectKey=portal-app" | jq -r .projectStatus.status)
-          echo $STATUS
-          if [ "$STATUS" != "OK" ]; then
-            echo "❌ ❌ Quality Gate Failed. Stoping deployment!! ❌ ❌ "
-            exit 1
-          fi
+    # ### SonarQube Quality Gates
+    #   - name: Check SonarQube Quality Gate
+    #     env:
+    #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+    #     run: |
+    #       STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonarqube.spontansolutions.com/api/qualitygates/project_status?projectKey=portal-app" | jq -r .projectStatus.status)
+    #       echo $STATUS
+    #       if [ "$STATUS" != "OK" ]; then
+    #         echo "❌ ❌ Quality Gate Failed. Stoping deployment!! ❌ ❌ "
+    #         exit 1
+    #       fi
 
-# #################################### Build Phase ########################################
+#################################### Build Phase ########################################
 
     ### Downloading portal-app.js
       - name: Downloading portal-app.js from AWS
@@ -108,12 +108,12 @@ jobs:
           cd app-Frontend
           tar -czf portal-app-$DATE.tar.gz node_modules package.json public portal-app.js
 
-    ### Uploading Artifact to Nexus
-      - name: Upload to Nexus
-        run: |
-          curl -u ${{ secrets.NEXUS_USER }}:${{ secrets.NEXUS_PASS }} \
-          --upload-file app-Frontend/portal-app-$DATE.tar.gz \
-          https://nexus.spontansolutions.com/repository/portal-app-artifacts/portal-app-$DATE.tar.gz
+    # ### Uploading Artifact to Nexus
+    #   - name: Upload to Nexus
+    #     run: |
+    #       curl -u ${{ secrets.NEXUS_USER }}:${{ secrets.NEXUS_PASS }} \
+    #       --upload-file app-Frontend/portal-app-$DATE.tar.gz \
+    #       https://nexus.spontansolutions.com/repository/portal-app-artifacts/portal-app-$DATE.tar.gz
 
     ### Uploading Artifact to S3
       - name: Uploading Artifact to S3 Bucket
@@ -121,70 +121,38 @@ jobs:
           cd app-Frontend
           aws s3 cp portal-app-$DATE.tar.gz s3://portal-app-spontansolutions/github-actions/
 
-    # ### Installing Docker 
-    #   - name: Set up Docker
-    #     uses: docker/setup-docker-action@v4
+    ### Build Docker Image
+      - name: Build Portal-app Docker Image
+        uses: docker/build-push-action@v6
+        with:
+          context: app-Frontend
+          dockerfile: Dockerfile
+          push: false
+          tags: ${{ secrets.DOCKERHUB_USERNAME }}/portal-app:${{ env.DATE }}
 
-    #   - name: Set image tag with date
-    #     run: echo "IMAGE_TAG=portal-app:$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV
+      - name: Scan local Docker image with Trivy
+        uses: aquasecurity/trivy-action@0.28.0
+        with:
+          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/portal-app:${{ env.DATE }}
+          format: 'table'
+          ignore-unfixed: true
+          severity: 'CRITICAL,HIGH'
 
-#     ### Docker Login
-#       - name: Login Docker Hub
-#         uses: docker/login-action@v3
-#         with:
-#           username: ${{ secrets.DOCKERHUB_USERNAME }}
-#           password: ${{ secrets.DOCKERHUB_PASSWORD }}
+    ### Docker Login
+      - name: Login Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
-      # - name: Install Trivy
-      #   run: |
-      #     sudo apt-get install wget apt-transport-https gnupg lsb-release
-      #     wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
-      #     echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
-      #     sudo apt-get update -y
-      #     sudo apt-get install -y trivy
-
-    # ### Build Docker Image
-    #   - name: Build Portal-app Docker Image
-    #     uses: docker/build-push-action@v6
-    #     with:
-    #       context: app-Frontend
-    #       dockerfile: Dockerfile
-    #       push: false
-    #       tags: $IMAGE_TAG
-
-      # - name: Build Docker image
-      #   run: |
-      #     cd app-Frontend
-      #     docker build -t $IMAGE_TAG .
-
-      # - name: Scan local Docker image with Trivy
-      #   uses: aquasecurity/trivy-action@master
-      #   with:
-      #     image-ref: $IMAGE_TAG
-      #     format: 'table'
-      #     severity: 'CRITICAL,HIGH'
-
-#       # - name: Run Trivy Scan on Local Docker Image
-#       #   run: |
-#       #     echo "1234"
-#       #     docker images
-#       #     echo "5678"
-#       #     trivy image --severity HIGH,CRITICAL portal-app:latest
-#         # trivy image --severity HIGH,CRITICAL portal-app:${{ env.DATE }}
-
-#       # - name: Tag Docker Image
-#       #   run: |
-#       #     docker tag portal-app:${{ env.DATE }} ${{ secrets.DOCKERHUB_USERNAME }}/portal-app:${{ env.DATE }}
-
-
-#     ### Push to Docker Hub
-#       - name: Push Portal-app to Docker Hub
-#         uses: docker/build-push-action@v6
-#         with:
-#           context: app-Frontend
-#           dockerfile: Dockerfile
-#           push: true
-#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/portal-app:${{ env.DATE }}
+    ### Push to Docker Hub
+      - name: Push Portal-app to Docker Hub
+        uses: docker/build-push-action@v6
+        with:
+          context: app-Frontend
+          dockerfile: Dockerfile
+          push: true
+          tags: ${{ secrets.DOCKERHUB_USERNAME }}/portal-app:${{ env.DATE }}
 
 #   ### Docker Image Scan by Trivy
 #       - name: Run Trivy Docker Image Scan (Docker Image Scan)
@@ -198,32 +166,31 @@ jobs:
 #           # severity: 'CRITICAL,HIGH'
 
 
+    ### 🚨 Send Slack Alert on Failure
+      - name: Send Slack Alert on Failure
+        if: failure()
+        run: |
+          curl -X POST -H 'Content-type: application/json' --data '{
+            "attachments": [
+              {
+                "color": "#FF0000",
+                "title": "🚨 CI/CD Pipeline Failed!",
+                "text": "❌ Repository: ${{ github.repository }}\nBranch: ${{ github.ref }}\nCheck logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+              }
+            ]
+          }' ${{ secrets.SLACK_WEBHOOK_URL }}
 
-    # ### 🚨 Send Slack Alert on Failure
-    #   - name: Send Slack Alert on Failure
-    #     if: failure()
-    #     run: |
-    #       curl -X POST -H 'Content-type: application/json' --data '{
-    #         "attachments": [
-    #           {
-    #             "color": "#FF0000",
-    #             "title": "🚨 CI/CD Pipeline Failed!",
-    #             "text": "❌ Repository: ${{ github.repository }}\nBranch: ${{ github.ref }}\nCheck logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-    #           }
-    #         ]
-    #       }' ${{ secrets.SLACK_WEBHOOK_URL }}
-
-    # ### ✅ Send Slack Alert on Success
-    #   - name: Send Slack Alert on Success
-    #     if: success()
-    #     run: |
-    #       curl -X POST -H 'Content-type: application/json' --data '{
-    #         "attachments": [
-    #           {
-    #             "color": "#36A64F",
-    #             "title": "✅ CI/CD Pipeline Succeeded!",
-    #             "text": "🎉 Repository: ${{ github.repository }}\nBranch: ${{ github.ref }}\nCheck logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-    #           }
-    #         ]
-    #       }' ${{ secrets.SLACK_WEBHOOK_URL }}
+    ### ✅ Send Slack Alert on Success
+      - name: Send Slack Alert on Success
+        if: success()
+        run: |
+          curl -X POST -H 'Content-type: application/json' --data '{
+            "attachments": [
+              {
+                "color": "#36A64F",
+                "title": "✅ CI/CD Pipeline Succeeded!",
+                "text": "🎉 Repository: ${{ github.repository }}\nBranch: ${{ github.ref }}\nCheck logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+              }
+            ]
+          }' ${{ secrets.SLACK_WEBHOOK_URL }}
 
