added Quality Gates profile to portal-app

diff --git a/.github/workflows/portal-app-CI.yaml b/.github/workflows/portal-app-CI.yaml
--- a/.github/workflows/portal-app-CI.yaml
+++ b/.github/workflows/portal-app-CI.yaml
@@ -58,6 +58,14 @@ jobs:
           -Dsonar.host.url=https://sonarqube.spontansolutions.com/ \
           -Dsonar.login=$SONAR_TOKEN
 
+    ### SonarQube Quality Gates
+      - name: Check SonarQube Quality Gate
+        run: |
+          STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonarqube.spontansolutions.com//api/qualitygates/project_status?projectKey=portal-app" | jq -r .projectStatus.status)
+          if [ "$STATUS" != "OK" ]; then
+            echo "XXXX Quality Gate Failed. Stoping deployment!! XXXX"
+            exit 1
+          fi
 
 #################################### Build Phase ########################################
 
